### ISSUE TITLE
Unnecessary packages

### ISSUE THREAD

**Issue by HENRYMARTIN5** [GoDzM4TT3O/Arch#4]
In the "Install a Desktop Environment" section in this guide, it claims that you need to install `gnome` and `budgie-desktop` to use Budgie as your DE, but that's not quite right. `gnome` is actually a group that contains many various packages required for the GNOME desktop, and the only package that's really required is `gdm`, the GNOME Display Manager.

**Comment by saloniamatteo** [comment]
Fixed with commit a4dfeed.
